import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import QueryProvider from "@/components/query-provider";
import Navbar from "@/components/ui/Navbar";
import Uploader from "@/components/ui/Uploader";
import { Toaster } from "@/components/ui/sonner";
import ThumbnailUploader from "@/components/ui/ThumbnailUploader";
import PostsMaker from "@/components/ui/PostsMaker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <QueryProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <main className="max-w-6xl min-h-screen mx-auto">
                                <Navbar />
                                {children}
                            </main>
                            <Toaster richColors />
                        </ThemeProvider>
                        <Uploader />
                        <PostsMaker />
                    </QueryProvider>
                </body>
            </html>
        </>
    );
}
